
read_liberty /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/global/NangateOpenCellLibrary_typical.lib
read_verilog /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/Yash/8x8/gate_level_netlists/10-temp_gate_level.v
link_design rr8x8__B__rr5x5__B__rr3x3__B__nr1x1__nr1x2__nr2x1__nr2x2__B__nr3x2__nr2x3__nr2x2__B__nr5x3__nr3x5__rr3x3__B__nr2x2__nr2x1__nr1x2__nr1x1__B__B__
read_sdc /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/global/test.sdc
report_power > /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/Yash/8x8/reports/power_reports/10-temp_power.txt
report_checks > /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/Yash/8x8/reports/delay_reports/10-temp_delay.txt
exit
