
read_liberty /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/global/NangateOpenCellLibrary_typical.lib
read_verilog /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/Yash/8x8/gate_level_netlists/16-temp_gate_level.v
link_design rr8x8__B__nr1x1__nr1x7__nr7x1__rr7x7__B__nr3x3__nr3x4__nr4x3__rr4x4__B__nr2x2__nr2x2__nr2x2__nr2x2__B__B__B__
read_sdc /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/global/test.sdc
report_power > /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/Yash/8x8/reports/power_reports/16-temp_power.txt
report_checks > /home/asus/Desktop/MR_PE/Emerging_Multiplier_Architectures/Yash/8x8/reports/delay_reports/16-temp_delay.txt
exit
