/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module FA(a, b, cin, sum, carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  input cin;
  wire cin;
  output sum;
  wire sum;
  INV_X1 _11_ (
    .A(_06_),
    .ZN(_07_)
  );
  NAND2_X1 _12_ (
    .A1(_04_),
    .A2(_03_),
    .ZN(_08_)
  );
  XNOR2_X1 _13_ (
    .A(_04_),
    .B(_03_),
    .ZN(_09_)
  );
  XNOR2_X1 _14_ (
    .A(_06_),
    .B(_09_),
    .ZN(_10_)
  );
  OAI21_X1 _15_ (
    .A(_08_),
    .B1(_09_),
    .B2(_07_),
    .ZN(_05_)
  );
  assign _04_ = b;
  assign _03_ = a;
  assign _06_ = cin;
  assign sum = _10_;
  assign carry = _05_;
endmodule

module HA(a, b, sum, carry);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  output sum;
  wire sum;
  AND2_X1 _4_ (
    .A1(_1_),
    .A2(_0_),
    .ZN(_2_)
  );
  XOR2_X1 _5_ (
    .A(_1_),
    .B(_0_),
    .Z(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign sum = _3_;
  assign carry = _2_;
endmodule

module exact_3x2(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input [2:0] A;
  wire [2:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [4:0] P;
  wire [4:0] P;
  wire c1;
  wire c2;
  wire pp0;
  wire pp1;
  wire pp2;
  wire pp3;
  wire pp4;
  wire pp5;
  AND2_X1 _11_ (
    .A1(_03_),
    .A2(_00_),
    .ZN(_05_)
  );
  AND2_X1 _12_ (
    .A1(_03_),
    .A2(_01_),
    .ZN(_06_)
  );
  AND2_X1 _13_ (
    .A1(_03_),
    .A2(_02_),
    .ZN(_07_)
  );
  AND2_X1 _14_ (
    .A1(_00_),
    .A2(_04_),
    .ZN(_08_)
  );
  AND2_X1 _15_ (
    .A1(_01_),
    .A2(_04_),
    .ZN(_09_)
  );
  AND2_X1 _16_ (
    .A1(_02_),
    .A2(_04_),
    .ZN(_10_)
  );
  FA fa (
    .a(pp2),
    .b(pp4),
    .carry(c2),
    .cin(c1),
    .sum(P[2])
  );
  HA ha1 (
    .a(pp1),
    .b(pp3),
    .carry(c1),
    .sum(P[1])
  );
  HA ha2 (
    .a(c2),
    .b(pp5),
    .carry(P[4]),
    .sum(P[3])
  );
  assign P[0] = pp0;
  assign _03_ = B[0];
  assign _00_ = A[0];
  assign pp0 = _05_;
  assign _01_ = A[1];
  assign pp1 = _06_;
  assign _02_ = A[2];
  assign pp2 = _07_;
  assign _04_ = B[1];
  assign pp3 = _08_;
  assign pp4 = _09_;
  assign pp5 = _10_;
endmodule
