/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module exact_3x2_mult_op(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  input [2:0] A;
  wire [2:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [4:0] P;
  wire [4:0] P;
  AND2_X1 _30_ (
    .A1(_16_),
    .A2(_13_),
    .ZN(_18_)
  );
  NAND2_X1 _31_ (
    .A1(_13_),
    .A2(_17_),
    .ZN(_23_)
  );
  NAND2_X1 _32_ (
    .A1(_16_),
    .A2(_14_),
    .ZN(_24_)
  );
  NAND4_X1 _33_ (
    .A1(_16_),
    .A2(_13_),
    .A3(_17_),
    .A4(_14_),
    .ZN(_25_)
  );
  AOI22_X1 _34_ (
    .A1(_16_),
    .A2(_15_),
    .B1(_17_),
    .B2(_14_),
    .ZN(_26_)
  );
  AND4_X1 _35_ (
    .A1(_16_),
    .A2(_15_),
    .A3(_17_),
    .A4(_14_),
    .ZN(_22_)
  );
  OR3_X1 _36_ (
    .A1(_25_),
    .A2(_26_),
    .A3(_22_),
    .ZN(_27_)
  );
  OAI21_X1 _37_ (
    .A(_25_),
    .B1(_26_),
    .B2(_22_),
    .ZN(_28_)
  );
  AND2_X1 _38_ (
    .A1(_27_),
    .A2(_28_),
    .ZN(_20_)
  );
  NAND2_X1 _39_ (
    .A1(_15_),
    .A2(_17_),
    .ZN(_29_)
  );
  OAI21_X1 _40_ (
    .A(_27_),
    .B1(_29_),
    .B2(_22_),
    .ZN(_21_)
  );
  XOR2_X1 _41_ (
    .A(_23_),
    .B(_24_),
    .Z(_19_)
  );
  assign _16_ = B[0];
  assign _13_ = A[0];
  assign P[0] = _18_;
  assign _15_ = A[2];
  assign _17_ = B[1];
  assign _14_ = A[1];
  assign P[2] = _20_;
  assign P[3] = _21_;
  assign P[1] = _19_;
  assign P[4] = _22_;
endmodule
